export {default as Home} from './Home'
export {default as Store} from './Store'
export {default as Login} from './Login'
export {default as Cart} from './Cart'
export {default as SignUp} from './SignUp'
export {default as Accessories} from './Accessories'
export {default as Macbook} from './Macbook'